# Generated by Django 2.0.1 on 2018-01-28 11:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import rest.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 1, 28, 11, 12, 2, 340884))),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=400)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word',
                 models.CharField(max_length=200, unique=True, validators=[rest.validators.LowerCaseUnique])),
            ],
        ),
        migrations.AddField(
            model_name='vacancies',
            name='key_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies',
                                    to='django_rest.Word'),
        ),
        migrations.AlterUniqueTogether(
            name='vacancies',
            unique_together={('url', 'id')},
        ),
    ]
