# Generated by Django 2.0.1 on 2018-01-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancies',
            old_name='ref',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='word',
            name='users',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='title',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
