# Generated by Django 2.0.1 on 2018-01-29 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('django_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 1, 29, 2, 30, 0, 710743)),
        ),
    ]
